課題を提出します.
prg1-2018/assignment1 pull request #10
Opened 2018-10-11 09:03 UTC by 17b17125

発展課題を行いました.
発展課題と行列を用いる方法とで1000番目のフィボナッチ数がいっちしていることは確認しました.

2018-10-17 05:46 UTC, nanashima requested changes
テストケースを追加し，テストに通ることを確認して提出してください．
プログラムはもっとシンプルにかける箇所は色々ありそうです．
例えば，isEven(n) match は単純に (n%2) match でかけます．

2018-10-17 05:46 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
> +     fib_matrix(1000) should equal(fib_polynomial(1000))
・テストケースが単純に少ないです（特にmatrixやpolynomial）．
・0などの誤りやすそうなケースも追加しましょう．
・fib_rec(100)を呼んでいますが，ちゃんとテストを走らせて止まりましたか？ matrixはitrを使ってテストすれば良いです．

2018-10-18 10:46 UTC, 17b17125 commented
不十分な点の指摘、助言ありがとうございます。
set でテストを作り、通るということがどういう状況か前回の提出時点でわかっていませんでした。
テストを整備し、 isEven の部分を変更しました。
その他について修正は加えていません。よろしくお願いします。

2018-10-23 02:20 UTC, nanashima approved these changes

2018-10-23 02:20 UTC, nanashima commented on src/assignment1-fibonacci.scala
> +        f2;
ここを上手くやればnのmatch式は削れそうですね．

2018-10-23 02:20 UTC, nanashima commented on src/assignment1-fibonacci.scala
> +        var ma = new Array[BigInt](4);
var ma = Array (1,1,1,0)なんて一気に書けたりもします．

2018-10-23 02:20 UTC, nanashima commented on src/assignment1-fibonacci.scala
> +              var c = new Array[BigInt](4);
こことかも　Array(1,0,0,1) でよさそうですね

2018-10-23 02:20 UTC, closed without merging