課題を提出します
prg1-2018/assignment1 pull request #13
Opened 2018-10-13 04:41 UTC by Yutaro-Sanada

2018-10-13 04:41 UTC, Yutaro-Sanada commented
発展課題は時間があれば提出します

2018-10-17 05:52 UTC, nanashima requested changes
テストケースを修正して，きちんと通ることを確認して提出してください．

2018-10-17 05:52 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
> +    }
・fib_rec(100)を呼んでいますが，ちゃんとテストを走らせて止まりましたか？ itrをrecを使って（小さい値で）テストした後，matrixはitrを使ってテストすれば良いです．
・0など誤りやすそうなケースも追加しておきましょう．

2018-10-17 07:47 UTC, Yutaro-Sanada commented on test/assignment1-fibonaccitest.scala
> +    }
修正しました。

2018-10-17 08:01 UTC, nanashima approved these changes

2018-10-17 08:01 UTC, closed without merging