発展課題はやっていません。
prg1-2018/assignment1 pull request #14
Opened 2018-10-13 09:41 UTC by makinzm

2018-10-17 05:55 UTC, nanashima requested changes
テストケースを追加して提出してください．

2018-10-17 05:55 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
> +     fib_matrix(20) should equal (fib_rec(20))
・0などの誤りやすそうなケースを追加しましょう．
・計算結果がIntに収まらないケースも追加しましょう(n=100とか1000とか)．その際効率が悪いrecを使うと止まらないはずなので，matrixとitrが等しいことをテストすると良いです．

2018-10-19 03:25 UTC, makinzm commented
訂正しました。よろしくお願いいたします。

2018-10-23 02:47 UTC, nanashima requested changes

2018-10-23 02:47 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
}が足りないです．テストは走らせてから提出しましょう．

2018-10-23 04:45 UTC, makinzm commented
再度訂正いたしました。

2018-10-23 06:01 UTC, nanashima approved these changes

2018-10-23 06:02 UTC, closed without merging