課題を提出します。
prg1-2018/assignment1 pull request #19
Opened 2018-10-14 13:40 UTC by ikamentai-aya

発展課題はやっていません。

2018-10-17 06:01 UTC, nanashima requested changes
テストを修正して提出してください．このままではテストは動かないはずです．
(今後もテストを書いて，それがきちんと通ることを確認してから課題を提出しましょう．)

2018-10-17 06:01 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
> +     fib_itr(1) should equal (fib_rec(1))     fib_itr(2) should equal (fib_rec(2))
二行で書くか，セミコロン(;)で分けましょう．

2018-10-17 06:01 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
> +     fib_matrix(1) should equal (fib_rec(1))     fib_matrix(2) should equal (fib_rec(2))
ここもです

2018-10-17 06:01 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
> +     ib_matrix(100) should equal (fib_rec(100))
ib_matrix??
fib_recは効率が悪いので100くらいだともう止まらないはずです．
fib_matrixはitrを使ってテストすれば良いです．

2018-11-09 05:45 UTC, ikamentai-aya commented
修正しました。
大変遅くなってしまって申し訳ございません。

2018-11-13 06:12 UTC, nanashima approved these changes

2018-11-13 06:12 UTC, closed without merging