課題を提出します
prg1-2018/assignment1 pull request #22
Opened 2018-10-14 16:11 UTC by riemasukawa

発展課題はできていません。

2018-10-17 06:06 UTC, nanashima requested changes
テストを修正して提出してください．
今後もテストがきちんと通ることを確認してから課題を提出しましょう．

2018-10-17 06:06 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
> +     fib_matrix(100) should equal (fib_rec(20))
そもそもテストが間違えています．テストを走らせましたか？

2018-10-17 06:06 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
>     }
fib_recは効率が悪く，n=100くらいにするともう止まらないはずです．
fib_matrixはfib_itrを使ってテストすれば良いです．
あと，0などの誤りやすそうなケースも追加しましょう．

2018-10-22 05:58 UTC, riemasukawa commented
修正しました。
間違えたコードを書いてもテストでsuccessと一行表示されるだけで、正しくテストされず、どうすれば良いか分かりません。

2018-10-22 05:59 UTC, riemasukawa commented
修正しました。
間違えたコードを書いてもテストでsuccessと一行表示されるだけで、正しくテストされず、どうすれば良いか分かりません。

2018-10-22 05:59 UTC, riemasukawa commented
修正しました。
間違えたコードを書いてもテストでsuccessと一行表示されるだけで、正しくテストされず、どうすれば良いか分かりません。

2018-10-22 06:02 UTC, riemasukawa commented
修正しました。
間違えたコードでテストを実行しても、successと一行表示されるだけで、正しくテストされません。何が原因でしょうか‥

2018-10-22 11:33 UTC, riemasukawa commented
修正しました。
間違えたコードでテストを実行しても、successと一行だけ表示されてしまうのですが、原因が分かりません。

2018-10-23 02:25 UTC, nanashima commented
???
カレントディレクトリはどこでテストを実行していますか？
build.sbtがある場所でsbtを起動しないと正しくテストできないかと思います．

2018-10-23 02:26 UTC, nanashima approved these changes

2018-10-23 02:26 UTC, closed without merging