課題を提出します
prg1-2018/assignment1 pull request #35
Opened 2018-10-15 08:41 UTC by nnneonnn

発展課題はできていません。

2018-10-16 11:46 UTC, nanashima requested changes
fib_itrを修正してください．
ミスに気付くためにも，テストをしっかり書きましょう．

2018-10-16 11:46 UTC, nanashima commented on src/assignment1-fibonacci.scala
> +    def fib_itr_sub(a:Int, b:Int,m:Int): BigInt = (a,b,m) match {
a,bはBigIntとしないと桁あふれします．

2018-10-16 11:46 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
> +     fib_matrix(0) should equal (fib_itr(0))
テストが不十分です．0でテストしている点は良いですが，それぞれもっと多くの点でテストをしてください．
特にfib_itrを使ってfib_matrixのテストをする際には，計算結果がIntで収まらない範囲までテストしましょう．

2018-10-17 05:06 UTC, nnneonnn commented
ご指摘いただいた箇所を修正しました。

2018-10-17 08:05 UTC, nanashima approved these changes

2018-10-17 08:05 UTC, closed without merging