課題1提出します
prg1-2018/assignment1 pull request #36
Opened 2018-10-15 08:58 UTC by kazuya-kawahara

発展課題は時間がないのであとで考えたいと思います。

2018-10-16 11:51 UTC, nanashima requested changes
fib_itrを修正してください．
テストケースももう少し増やしましょう．

2018-10-16 11:51 UTC, nanashima commented on src/assignment1-fibonacci.scala
> +    def sub_itr(a: Int, b: Int, m: Int): BigInt = {
a,bはBigIntとしないと桁あふれします．

2018-10-16 11:51 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
> +     fib_matrix(100) should equal (fib_itr(100))
ここのテストが通っていないはずです．テストに通ることを確認して提出してください．
あと，fib_matrixのテストが0と一点のみは流石に少ないかと思います．

2018-10-18 03:30 UTC, kazuya-kawahara commented
修正しました。残りは効率は置いといて動作には問題ないと思います。
よろしくお願いします。

2018-10-18 08:04 UTC, nanashima approved these changes

2018-10-18 08:04 UTC, closed without merging