kadai
prg1-2018/assignment1 pull request #8
Opened 2018-10-11 06:01 UTC by 17B01035

発展的課題以外はできました

2018-10-17 06:46 UTC, nanashima requested changes
テストケースを追加して提出してください．

2018-10-17 06:46 UTC, nanashima commented on test/assignment1-fibonaccitest.scala
> +	fib_matrix(100) should equal (fib_itr(100))
・テストケースが一点は流石に少ないです．
・0などの誤りやすそうなケースも追加しましょう．

2018-10-18 06:06 UTC, 17B01035 commented
テスト追加しました

2018-10-18 08:00 UTC, nanashima approved these changes

2018-10-18 08:00 UTC, closed without merging